# Generated by Django 4.0.6 on 2022-07-16 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField(default=django.utils.timezone.now)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "DEFAULT"),
                            ("PERSONAL", "PERSONAL"),
                            ("FAMILY", "FAMILY"),
                            (" WORK", " WORK"),
                        ],
                        default="DEFAULT",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
