# название
name: AutomationTest

# целевые события для запуска
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# выполняемые действия
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: npm ci
    - name: Run Makefile test
      run: npm test
